In [ ]:
#Data manipulation
import pandas as pd
import numpy as np

# Data Visulization

import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning & Preprocessing

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Machine Learning Model
from sklearn.linear_model import LinearRegression

# Model Evaluation
from sklearn.metrics import mean_absolute_error

In [ ]:
data=pd.read_csv("/content/Customer_Payment_Default_Dataset.csv")
data

,Record_ID,Age,Annual_Income,Credit_Score,Loan_Amount,Debt_to_Income_Ratio,Employment_Type,Region,Has_Previous_Default,Owns_House,Account_Open_Date,Target_Column
0,100821,29.0,42519.15,520.0,16283.72,NaN,Salaried,West,0,0,2019-01-05,1
1,100058,51.0,56301.50,609.0,28567.71,54.31,Self-Employed,South,0,1,2024-12-27,1
2,100972,37.0,65326.52,713.0,12033.37,23.14,Salaried,North,0,1,2020-10-24,0
3,100670,35.0,59021.99,598.0,23246.10,32.19,Salaried,West,0,0,2024-09-05,1
4,100739,33.0,50408.54,587.0,16845.28,43.03,Salaried,North,0,0,2018-12-01,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,101093,27.0,50633.21,585.0,11967.78,16.61,Salaried,East,0,0,2018-12-18,0
1496,101193,37.0,46760.78,701.0,19879.84,32.73,Business Owner,South,0,0,2018-04-14,0
1497,101210,49.0,55878.94,603.0,13454.39,28.08,Salaried,South,0,0,2019-02-26,1
1498,101060,42.0,66507.79,619.0,18524.47,31.26,Self-Employed,East,1,1,2018-04-08,0
1499,100642,43.0,84959.44,709.0,22394.32,30.33,Business Owner,South,0,1,2018-10-14,0

In [ ]:
data.head()

,Record_ID,Age,Annual_Income,Credit_Score,Loan_Amount,Debt_to_Income_Ratio,Employment_Type,Region,Has_Previous_Default,Owns_House,Account_Open_Date,Target_Column
0,100821,29.0,42519.15,520.0,16283.72,NaN,Salaried,West,0,0,2019-01-05,1
1,100058,51.0,56301.50,609.0,28567.71,54.31,Self-Employed,South,0,1,2024-12-27,1
2,100972,37.0,65326.52,713.0,12033.37,23.14,Salaried,North,0,1,2020-10-24,0
3,100670,35.0,59021.99,598.0,23246.10,32.19,Salaried,West,0,0,2024-09-05,1
4,100739,33.0,50408.54,587.0,16845.28,43.03,Salaried,North,0,0,2018-12-01,0

In [ ]:
data.tail()

,Record_ID,Age,Annual_Income,Credit_Score,Loan_Amount,Debt_to_Income_Ratio,Employment_Type,Region,Has_Previous_Default,Owns_House,Account_Open_Date,Target_Column
1495,101093,27.0,50633.21,585.0,11967.78,16.61,Salaried,East,0,0,2018-12-18,0
1496,101193,37.0,46760.78,701.0,19879.84,32.73,Business Owner,South,0,0,2018-04-14,0
1497,101210,49.0,55878.94,603.0,13454.39,28.08,Salaried,South,0,0,2019-02-26,1
1498,101060,42.0,66507.79,619.0,18524.47,31.26,Self-Employed,East,1,1,2018-04-08,0
1499,100642,43.0,84959.44,709.0,22394.32,30.33,Business Owner,South,0,1,2018-10-14,0

In [ ]:
#Checking dataset Shape
data.shape

(1500, 12)

In [ ]:
# Checking all dataset types
data.dtypes

Record_ID                 int64
Age                     float64
Annual_Income           float64
Credit_Score            float64
Loan_Amount             float64
Debt_to_Income_Ratio    float64
Employment_Type          object
Region                   object
Has_Previous_Default      int64
Owns_House                int64
Account_Open_Date        object
Target_Column             int64
dtype: object

In [ ]:
# Dataset Information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Record_ID             1500 non-null   int64
 1   Age                   1473 non-null   float64
 2   Annual_Income         1474 non-null   float64
 3   Credit_Score          1473 non-null   float64
 4   Loan_Amount           1474 non-null   float64
 5   Debt_to_Income_Ratio  1474 non-null   float64
 6   Employment_Type       1474 non-null   object
 7   Region                1474 non-null   object
 8   Has_Previous_Default  1500 non-null   int64
 9   Owns_House            1500 non-null   int64
 10  Account_Open_Date     1474 non-null   object
 11  Target_Column         1500 non-null   int64
dtypes: float64(5), int64(4), object(3)
memory usage: 140.8+ KB

In [ ]:
#checking total missing value percentage
(data.isnull().sum() / len(data)) * 100

Record_ID               0.000000
Age                     1.800000
Annual_Income           1.733333
Credit_Score            1.800000
Loan_Amount             1.733333
Debt_to_Income_Ratio    1.733333
Employment_Type         1.733333
Region                  1.733333
Has_Previous_Default    0.000000
Owns_House              0.000000
Account_Open_Date       1.733333
Target_Column           0.000000
dtype: float64

In [ ]:
#stastical summary
data.describe()

,Record_ID,Age,Annual_Income,Credit_Score,Loan_Amount,Debt_to_Income_Ratio,Has_Previous_Default,Owns_House,Target_Column
count,1500.000000,1473.000000,1474.000000,1473.000000,1474.000000,1474.000000,1500.000000,1500.000000,1500.000000
mean,100733.408667,38.542430,59549.611947,620.054990,25271.450977,38.092028,0.142667,0.430000,0.278667
std,424.613159,10.602361,36468.066948,78.804521,47329.172911,21.127455,0.349849,0.495241,0.448493
min,100001.000000,20.000000,8000.000000,384.000000,1000.000000,1.650000,0.000000,0.000000,0.000000
25%,100367.750000,31.000000,44694.445000,569.000000,12785.815000,23.652500,0.000000,0.000000,0.000000
50%,100729.500000,38.000000,58580.580000,623.000000,20063.310000,35.625000,0.000000,0.000000,0.000000
75%,101100.250000,45.000000,70561.390000,675.000000,28837.175000,48.762500,0.000000,1.000000,1.000000
max,101470.000000,82.000000,493909.630000,848.000000,672335.120000,216.340000,1.000000,1.000000,1.000000

In [24]:
# Duplicate Value
data.duplicated().sum()

np.int64(30)