In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dict1 = {
    "name": ["manish", "rohit", "saurabh", "om","sarthak"],
    "marks": [92, 34, 24, 17, 88],
    "city": ["rampur", "kolkata", "bareilly", "antarctica", "dubai"]
}

In [ ]:
df = pd.DataFrame(dict1)

In [ ]:
print(df)

      name  marks        city
0   manish     92      rampur
1    rohit     34     kolkata
2  saurabh     24    bareilly
3       om     17  antarctica
4  sarthak     88       dubai

In [ ]:
df.head(5)

      name  marks        city
0   manish     92      rampur
1    rohit     34     kolkata
2  saurabh     24    bareilly
3       om     17  antarctica
4  sarthak     88       dubai

In [ ]:
df.tail(5)

      name  marks        city
0   manish     92      rampur
1    rohit     34     kolkata
2  saurabh     24    bareilly
3       om     17  antarctica
4  sarthak     88       dubai

In [10]:
df.to_csv("cat.csv")

NameError: name 'df' is not defined